### ISSUE TITLE
Still seeing the "WARNING: Wrapping `Vararg`..." warnings with LoopVectorization v0.9.9 and VectorizationBase v0.14.3

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/LoopVectorization.jl#175]
_Originally mentioned in [this comment](https://github.com/mcabbott/Tullio.jl/pull/72#issuecomment-748442734) and [this comment](https://github.com/mcabbott/Tullio.jl/pull/72#issuecomment-748505052)._

---

Regarding the repeated `WARNING: Wrapping Vararg directly in UnionAll is deprecated (wrap the tuple instead)` warnings that only come up during precompilation - I'm still seeing those warnings.

I'm on Julia master with `LoopVectorization v0.9.8` and `VectorizationBase v0.14.3` (with AFAICT are the latest versions), and I see these warnings when I do `rm -rf ~/.julia/compiled/` and then run the Gaius.jl test suite.

**Comment by chriselrod** [comment]
It's fixed in 0.9.9. I guess I should tag a new release.

**Comment by DilumAluthge** [comment]
I'm still seeing this with `LoopVectorization v0.9.9` and `VectorizationBase v0.14.3`.

<details>

<summary>Example log: (click to expand)</summary>

```
$ rm -rf ~/.julia/compiled/
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0-DEV.130 (2020-12-20)
 _/ |\__'_|_|_|\__'_|  |  Commit 58d6684e5e (0 days old master)
|__/                   |

(@v1.7) pkg> test Gaius
     Testing Gaius
Status `/private/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_WQnYLc/Project.toml`
  [6e4b80f9] BenchmarkTools v0.5.0
  [bffe22d1] Gaius v0.3.0 `~/Downloads/Gaius.jl`
  [bdcacae8] LoopVectorization v0.9.9
  [09ab397b] StructArrays v0.4.4
  [c4a57d5a] UnsafeArrays v1.0.1
  [3d5dd08c] VectorizationBase v0.14.3
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [9a3f8284] Random `@stdlib/Random`
  [8dfed614] Test `@stdlib/Test`
Status `/private/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_WQnYLc/Manifest.toml`
  [79e6a3ab] Adapt v2.3.0
  [4fba245c] ArrayInterface v2.14.6
  [6e4b80f9] BenchmarkTools v0.5.0
  [9a962f9c] DataAPI v1.4.0
  [e2d170a0] DataValueInterfaces v1.0.0
  [ffbed154] DocStringExtensions v0.8.3
  [bffe22d1] Gaius v0.3.0 `~/Downloads/Gaius.jl`
  [0e44f5e4] Hwloc v1.1.0
  [615f187c] IfElse v0.1.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [682c06a0] JSON v0.21.1
  [bdcacae8] LoopVectorization v0.9.9
  [6fe1bfb0] OffsetArrays v1.4.1
  [69de0a69] Parsers v1.0.15
  [ae029012] Requires v1.1.2
  [476501e8] SLEEFPirates v0.6.1
  [09ab397b] StructArrays v0.4.4
  [3783bdb8] TableTraits v1.0.0
  [bd369af6] Tables v1.2.2
  [3a884ed6] UnPack v1.0.2
  [c4a57d5a] UnsafeArrays v1.0.1
  [3d5dd08c] VectorizationBase v0.14.3
  [e33a78d0] Hwloc_jll v2.2.0+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [f43a241f] Downloads `@stdlib/Downloads`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
     Testing Running tests...
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).Test Summary:                | Pass  Total
Float64 Matrix-Vector        |   24     24
Test Summary:                | Pass  Total
ComplexF64  Matrix-Vector    |   24     24
Test Summary:                | Pass  Total
Float32 Matrix-Vector        |   24     24
Test Summary:                | Pass  Total
Int64 Matrix-Vector          |   24     24
Test Summary:                | Pass  Total
ComplexInt32 Matrix-Vector   |   24     24
Test Summary:                | Pass  Total
Float64 CoVector-Matrix      |   48     48
Test Summary:                | Pass  Total
ComplexF32 CoVector-Matrix   |   48     48
Test Summary:                | Pass  Total
ComplexFloat64 Matrix-Matrix |   24     24
Test Summary:                | Pass  Total
Float64 Matrix-Matrix        |   60     60
Test Summary:                | Pass  Total
Float32 Matrix-Matrix        |   30     30
Test Summary:                | Pass  Total
Int64 Matrix-Matrix          |   30     30
Test Summary:                | Pass  Total
Int32 Matrix-Matrix          |   30     30
     Testing Gaius tests passed
```

</details>

**Comment by chriselrod** [comment]
```julia
> jm --depwarn=error
julia> versioninfo()
Julia Version 1.7.0-DEV.122
Commit 676ccf4eaa (2020-12-18 19:53 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, tigerlake)

julia> using LoopVectorization
[ Info: Precompiling LoopVectorization [bdcacae8-1622-11e9-2a5c-532679323890]
```

**Comment by chriselrod** [comment]
Deleting my full compile cache, I see that there is at least on in ArrayInterface.

**Comment by DilumAluthge** [comment]
Yeah I did `~/.julia/compiled` prior to running.

**Comment by DilumAluthge** [comment]
Here's what I do to reproduce:
1. `rm -rf ~/.julia/compiled`
2. Start Julia
3. In Julia: `] test Gaius`

**Comment by DilumAluthge** [comment]
> Deleting my full compile cache, I see that there is at least on in ArrayInterface.

Oh I see what you mean - you're saying the occurences in LoopVectorization have been fixed, but there are still some left in ArrayInterface.

**Comment by chriselrod** [comment]
Anyway, thanks @DilumAluthge for pointing it out!
Fixed in ArrayInterface:
https://github.com/SciML/ArrayInterface.jl/commit/57b03b300433c2bce2ffdc8ade97682b096bef89
Fixed in VectorizationBase:
https://github.com/chriselrod/VectorizationBase.jl/commit/ac538d2101f0774a6b923d8afc7179bcae89b0db
